Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
